// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmIkxmNm4EZGL86ZhB79g3W0Ht5l31Pic',
    appId: '1:602005078913:web:5267c89832d6be94da5e80',
    messagingSenderId: '602005078913',
    projectId: 'watch-901e9',
    authDomain: 'watch-901e9.firebaseapp.com',
    storageBucket: 'watch-901e9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-OsGotRc8xU5WAI-I5DLhEtgqHbGmXxo',
    appId: '1:602005078913:android:83ccda2e619921b3da5e80',
    messagingSenderId: '602005078913',
    projectId: 'watch-901e9',
    storageBucket: 'watch-901e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1_xtp-JyKIicf_iOcP3XJTx4Ouxx4GsA',
    appId: '1:602005078913:ios:4c87c446e813a552da5e80',
    messagingSenderId: '602005078913',
    projectId: 'watch-901e9',
    storageBucket: 'watch-901e9.firebasestorage.app',
    iosBundleId: 'com.example.whatch',
  );
}
